#!/usr/bin/env bash

load_workload_profile() {
    local profile="${1:-standard}"

    case "${profile}" in
        standard)
            DEFAULT_DECODE_INPUT_LEN=256
            DEFAULT_DECODE_OUTPUT_LEN=1024
            DEFAULT_DECODE_PROMPTS=240
            DEFAULT_DECODE_CONCURRENCY=16
            DEFAULT_DECODE_REQUEST_RATE=2.0

            DEFAULT_PREFILL_INPUT_LEN=16384
            DEFAULT_PREFILL_OUTPUT_LEN=8
            DEFAULT_PREFILL_PROMPTS=32
            DEFAULT_PREFILL_CONCURRENCY=2
            DEFAULT_PREFILL_REQUEST_RATE=0.5
            DEFAULT_PREFILL_DELAY=3
            ;;

        high)
            DEFAULT_DECODE_INPUT_LEN=256
            DEFAULT_DECODE_OUTPUT_LEN=1024
            DEFAULT_DECODE_PROMPTS=320
            DEFAULT_DECODE_CONCURRENCY=32
            DEFAULT_DECODE_REQUEST_RATE=2.5

            DEFAULT_PREFILL_INPUT_LEN=16384
            DEFAULT_PREFILL_OUTPUT_LEN=8
            DEFAULT_PREFILL_PROMPTS=64
            DEFAULT_PREFILL_CONCURRENCY=4
            DEFAULT_PREFILL_REQUEST_RATE=1.0
            DEFAULT_PREFILL_DELAY=3
            ;;

        burst)
            DEFAULT_DECODE_INPUT_LEN=256
            DEFAULT_DECODE_OUTPUT_LEN=1024
            DEFAULT_DECODE_PROMPTS=320
            DEFAULT_DECODE_CONCURRENCY=32
            DEFAULT_DECODE_REQUEST_RATE=2.5

            DEFAULT_PREFILL_INPUT_LEN=16384
            DEFAULT_PREFILL_OUTPUT_LEN=8
            DEFAULT_PREFILL_PROMPTS=48
            DEFAULT_PREFILL_CONCURRENCY=4
            DEFAULT_PREFILL_REQUEST_RATE=inf
            DEFAULT_PREFILL_DELAY=3
            ;;

        *)
            echo "ERROR: Unknown workload profile: ${profile}" >&2
            echo "Supported profiles: standard high burst" >&2
            return 1
            ;;
    esac

    export PROFILE="${profile}"

    export DECODE_INPUT_LEN="${DECODE_INPUT_LEN:-${DEFAULT_DECODE_INPUT_LEN}}"
    export DECODE_OUTPUT_LEN="${DECODE_OUTPUT_LEN:-${DEFAULT_DECODE_OUTPUT_LEN}}"
    export DECODE_PROMPTS="${DECODE_PROMPTS:-${DEFAULT_DECODE_PROMPTS}}"
    export DECODE_CONCURRENCY="${DECODE_CONCURRENCY:-${DEFAULT_DECODE_CONCURRENCY}}"
    export DECODE_REQUEST_RATE="${DECODE_REQUEST_RATE:-${DEFAULT_DECODE_REQUEST_RATE}}"
    export DECODE_SEED="${DECODE_SEED:-1}"

    export PREFILL_INPUT_LEN="${PREFILL_INPUT_LEN:-${DEFAULT_PREFILL_INPUT_LEN}}"
    export PREFILL_OUTPUT_LEN="${PREFILL_OUTPUT_LEN:-${DEFAULT_PREFILL_OUTPUT_LEN}}"
    export PREFILL_PROMPTS="${PREFILL_PROMPTS:-${DEFAULT_PREFILL_PROMPTS}}"
    export PREFILL_CONCURRENCY="${PREFILL_CONCURRENCY:-${DEFAULT_PREFILL_CONCURRENCY}}"
    export PREFILL_REQUEST_RATE="${PREFILL_REQUEST_RATE:-${DEFAULT_PREFILL_REQUEST_RATE}}"
    export PREFILL_SEED="${PREFILL_SEED:-2}"
    export PREFILL_DELAY="${PREFILL_DELAY:-${DEFAULT_PREFILL_DELAY}}"
}